name: CMake

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: sudo apt install -y qtcreator qtbase5-dev qt5-qmake cmake
    - run: mkdir build
    - run: mkdir install
    - run: cd build
    - run: cmake -DCMAKE_INSTALL_PREFIX=../install ../src
    - run: make -j $(nproc)
    - uses: actions/upload-artifact@v3
      with:
        name: built
        path: ../
